export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    description: "Noise cancelling over-ear headphones",
    price: 1999,
    category: "Electronics",
    image: "https://via.placeholder.com/200/500",
  },
  {
    id: 2,
    name: "Sports Shoes",
    description: "Lightweight running shoes",
    price: 1499,
    category: "Fashion",
    image: "https://via.placeholder.com/200/501",
  },
  {
    id: 3,
    name: "Coffee Mug",
    description: "Ceramic coffee mug 300ml",
    price: 299,
    category: "Home",
    image: "https://via.placeholder.com/200/502",
  },
  {
    id: 4,
    name: "Gaming Mouse",
    description: "High-precision gaming mouse with RGB",
    price: 999,
    category: "Electronics",
    image: "https://via.placeholder.com/200/503",
  },
  {
    id: 5,
    name: "Denim Jacket",
    description: "Classic blue denim jacket for all seasons",
    price: 2499,
    category: "Fashion",
    image: "https://via.placeholder.com/200/504",
  },
  {
    id: 6,
    name: "Smartphone Stand",
    description: "Adjustable aluminum stand for phones",
    price: 499,
    category: "Home",
    image: "https://via.placeholder.com/200/505",
  },
];
